{% set version = "2.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-prettygraphs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/prettyGraphs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/prettyGraphs/prettyGraphs_{{ version }}.tar.gz
  sha256: 26a80afa54c1dc62800b9ba7a3c3fa05f7b0b1aa7fb652e9ef0ed9f5304e466d

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('prettyGraphs')"           # [not win]
    - "\"%R%\" -e \"library('prettyGraphs')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=prettyGraphs
  license: GPL-2.0-only
  summary: Simple and crisp publication-quality graphics for the ExPosition family of packages. See An ExPosition of the Singular Value Decomposition in R (Beaton et al 2014) <doi:10.1016/j.csda.2013.11.006>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: prettyGraphs
# Type: Package
# Title: Publication-Quality Graphics
# Version: 2.1.6
# Date: 2018-12-17
# Author: Derek Beaton
# Maintainer: Derek Beaton <exposition.software@gmail.com>
# Description: Simple and crisp publication-quality graphics for the ExPosition family of packages. See An ExPosition of the Singular Value Decomposition in R (Beaton et al 2014) <doi:10.1016/j.csda.2013.11.006>.
# License: GPL-2
# Packaged: 2018-12-18 03:56:26 UTC; Derek
# BugReports: https://github.com/derekbeaton/ExPosition-Family_OLD
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2018-12-18 11:00:03 UTC
