travis:
  secure:
    BINSTAR_TOKEN: vl6qs5h2dl/lJie8MQGGZUVygsSXEiQB2ILkwMEr8kXKvtccwPdFl3KI0IyP6/LdHqVRWS2N98vCD3ni+58WNP/acvCeK68O8EAQMejQfdTf/zfmqjjsw6RuWz5EAlZSvgiwy7o/8DlK8c8N8ps/tCFdeTGSyNSGhI3IfXA9iv0hwOJ/ZFCDe71v26ZAnj5Iy+CUcu68I/Ia2viH6u0YYAaIFMc9GmeRS9HpiI+c+kUkMxFZJjYMiqWO4D+c9vyXuOIqhIBJBFrpZ4UsXLuaYv2xwXFYVz4qxDpzNGokM3JVc4RMlICytm+MndwpStjb2mTIac04DZWnlP+RcXAuACEHdy3xFY3/MJArPheFxZ38/L5cbgGobddO3Fd3Sqn+E+o7r3hBxV/uXreBJTu8xG5vk4RW2kYXYsAJ8VsnVKseAgJIeFCzljkyeVBkM/IGUPhmV7wMTwIjPaFBvIlTiYzE9FPITOZNjw4G21h7WQ56vfvhfuGDb6UD6x6yi9/u1KnTM70QcyjARabb/SewhY5aF7Oj1yaHxbzGiWXFGHY5yZFYX9zxWwe1FiSi6rgXqU9mC9jE1o2Fd85FRToYpit23FBsgadQ4JJC5uQBCZ90A84A/aF6nb3brwhewEpKvIqGmNP1MJQJbMi+UtokseSsg/T5+mCIOcbEzYk3mp4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
